### ISSUE TITLE
error on tanks and temples

### ISSUE THREAD

**Issue by stillwang96** [XYZ-qiyh/Learning-MVS-PyTorch#1]
Hi, when I test casmvsnet with the casmvsnet.ckpt you provided, it shows normal on DTU dataset. But on tanks and temples, when I use gipuma, it displays:

CUDA error at /home/fusibile-master/main.cpp:466 code=2(cudaErrorMemoryAllocation) "cudaMallocArray(&cuArray, &channelDesc, cols, rows)" 

when I don’t use gipuma, it displays:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anaconda3/envs/mvs/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/anaconda3/envs/mvs/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "test.py", line 421, in pcd_filter_worker
    scan_id = int(scan[4:])
ValueError: invalid literal for int() with base 10: 'torium'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 463, in <module>
    pcd_filter(testlist, args.num_worker)
  File "test.py", line 437, in pcd_filter
    p.map(partial_func, testlist)
  File "/home/anaconda3/envs/mvs/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/anaconda3/envs/mvs/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'torium'

I really need your help!!!!!!!!

**Comment by XYZ-qiyh** [comment]
你好！
1. 应该将test_tanks.sh文件中的第三行`TESTLIST="lists/dtu/test.txt"`改为`TESTLIST="lists/tanks/intermediate.txt"`
https://github.com/XYZ-qiyh/Learning-MVS-PyTorch/blob/12beb534e43c74f28139e3c925caaf28ead92ad9/CasMVSNet/test_tanks.sh#L3
2. Tanks and Temples数据集保存的点云文件名应为`Family.ply`, `Francis.ply`..这种格式；而DTU数据集保存的点云文件名为`scan1.ply`, `scan4.ply`。需要确定输出点云的文件名是正常的，看你的报错信息，有可能是这个问题。
3. Tanks and Temples数据集融合不妨用Python版本的融合程序，因为Gipuma融合点云时需要把场景中所有深度图都读取进去，像Family这种300幅视图的场景，需要24GB显存的显卡才可以胜任。

希望对你有帮助

**Comment by stillwang96** [comment]
我觉得大概率可能是第二个原因，因为现在就卡在了点云的生成上，请问这个问题该怎么改呀？
